var iStep = -1;
var aSteps = [
	'slide slide-1.html',
    'slide ascii.html',
    'slide ascii-art.txt',
    'load http://www.asciimation.co.nz/#',
    'slide vml.html',
    'slide vml.txt',
    'slide vml.png',
    'slide vrml-x3d.html',
    'slide vrml.txt',
    'slide vrml.jpg',
    'slide div-pixels.html',
    'slide life.html',
    'slide java.html',
    'load http://www.its.caltech.edu/~dannyc/fractals/simple.html',
    'slide flash.html',
    'slide flash.png',
    'slide vector-graphics.html',
    'slide whale-depixelation.jpg',
    'slide canvas.html',
    'canvas',
    'can',
    'var ctx = can.getContext(\'2d\');',
    'ctx.fillStyle=\'rgb(200,0,0)\';',
    'ctx.fillRect(10, 10, 55, 50);',
    'ctx.fillStyle=\'rgba(0, 0, 200, 0.5)\';',
    'ctx.fillRect(30, 30, 55, 50);',
    'clear-canvas',
    'ctx.fillRect(25,25,100,100);',
    'ctx.clearRect(45,45,60,60);',
    'ctx.strokeRect(50,50,50,50);',
    'clear-canvas',
    'ctx.beginPath();',
    'ctx.moveTo(75,50);',
    'ctx.lineTo(100,75);', 
    'ctx.lineTo(100,25);', 
    'ctx.fill();',
    'clear-canvas',
    'ctx.beginPath();',
    'ctx.arc(75,75,50,0,Math.PI*2,true); // Outer circle  ',
    'ctx.moveTo(110,75);  ',
    'ctx.arc(75,75,35,0,Math.PI,false);   // Mouth (clockwise)  ',
    'ctx.moveTo(65,65);  ',
    'ctx.arc(60,65,5,0,Math.PI*2,true);  // Left eye  ',
    'ctx.moveTo(95,65);  ',
    'ctx.arc(90,65,5,0,Math.PI*2,true);  // Right eye  ',
    'ctx.stroke();  ',
    'clear-canvas',
    'ctx.beginPath();  ',
    'ctx.moveTo(75,25);  ',
    'ctx.quadraticCurveTo(25,25,25,62.5);  ',
    'ctx.quadraticCurveTo(25,100,50,100);  ',
    'ctx.quadraticCurveTo(50,120,30,125);  ',
    'ctx.quadraticCurveTo(60,120,65,100);  ',
    'ctx.quadraticCurveTo(125,100,125,62.5);  ',
    'ctx.quadraticCurveTo(125,25,75,25);  ',
    'ctx.stroke();  ',
    'clear-canvas',
    'slide canvas-more.html',
    'slide svg-topic.html',
    'slide svg.txt',
    'slide svg.html',
    'slide svg-more.html',
    'slide webgl.html',
    'load http://www.zynaps.com/site/experiments/hexagon.html',
    'slide end.html',
];

function stepForward(n) {
    iStep = limitedAdd(iStep, n, 0, aSteps.length - 1);
}
